//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dmsdatabaseModel", "FK_roletable_profile", "profile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dms.profile), "roletable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(dms.roletable), true)]

#endregion

namespace dms
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dmsdatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dmsdatabaseEntities object using the connection string found in the 'dmsdatabaseEntities' section of the application configuration file.
        /// </summary>
        public dmsdatabaseEntities() : base("name=dmsdatabaseEntities", "dmsdatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dmsdatabaseEntities object.
        /// </summary>
        public dmsdatabaseEntities(string connectionString) : base(connectionString, "dmsdatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dmsdatabaseEntities object.
        /// </summary>
        public dmsdatabaseEntities(EntityConnection connection) : base(connection, "dmsdatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<roletable> roletables
        {
            get
            {
                if ((_roletables == null))
                {
                    _roletables = base.CreateObjectSet<roletable>("roletables");
                }
                return _roletables;
            }
        }
        private ObjectSet<roletable> _roletables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<profile> profiles
        {
            get
            {
                if ((_profiles == null))
                {
                    _profiles = base.CreateObjectSet<profile>("profiles");
                }
                return _profiles;
            }
        }
        private ObjectSet<profile> _profiles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the roletables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToroletables(roletable roletable)
        {
            base.AddObject("roletables", roletable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the profiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprofiles(profile profile)
        {
            base.AddObject("profiles", profile);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dmsdatabaseModel", Name="profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new profile object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="role">Initial value of the role property.</param>
        public static profile Createprofile(global::System.Int32 id, global::System.String username, global::System.String password, global::System.Int32 role)
        {
            profile profile = new profile();
            profile.id = id;
            profile.username = username;
            profile.password = password;
            profile.role = role;
            return profile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.Int32 _role;
        partial void OnroleChanging(global::System.Int32 value);
        partial void OnroleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                OnisActiveChanging(value);
                ReportPropertyChanging("isActive");
                _isActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isActive");
                OnisActiveChanged();
            }
        }
        private Nullable<global::System.Int32> _isActive;
        partial void OnisActiveChanging(Nullable<global::System.Int32> value);
        partial void OnisActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dmsdatabaseModel", "FK_roletable_profile", "roletable")]
        public roletable roletable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<roletable>("dmsdatabaseModel.FK_roletable_profile", "roletable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<roletable>("dmsdatabaseModel.FK_roletable_profile", "roletable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<roletable> roletableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<roletable>("dmsdatabaseModel.FK_roletable_profile", "roletable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<roletable>("dmsdatabaseModel.FK_roletable_profile", "roletable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dmsdatabaseModel", Name="roletable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class roletable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new roletable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="role">Initial value of the role property.</param>
        /// <param name="rolename">Initial value of the rolename property.</param>
        public static roletable Createroletable(global::System.Int32 id, global::System.Int32 role, global::System.String rolename)
        {
            roletable roletable = new roletable();
            roletable.id = id;
            roletable.role = role;
            roletable.rolename = rolename;
            return roletable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.Int32 _role;
        partial void OnroleChanging(global::System.Int32 value);
        partial void OnroleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rolename
        {
            get
            {
                return _rolename;
            }
            set
            {
                OnrolenameChanging(value);
                ReportPropertyChanging("rolename");
                _rolename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rolename");
                OnrolenameChanged();
            }
        }
        private global::System.String _rolename;
        partial void OnrolenameChanging(global::System.String value);
        partial void OnrolenameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dmsdatabaseModel", "FK_roletable_profile", "profile")]
        public profile profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<profile>("dmsdatabaseModel.FK_roletable_profile", "profile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<profile>("dmsdatabaseModel.FK_roletable_profile", "profile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<profile> profileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<profile>("dmsdatabaseModel.FK_roletable_profile", "profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<profile>("dmsdatabaseModel.FK_roletable_profile", "profile", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
